name: Test API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      env:
        access_token: ${{ secrets.CIDR_GIT_TOKEN }}
        occupied_repo: ${{ vars.OCCUPIED_REPO }}
        occupied_file: ${{ vars.OCCUPIED_FILE }}
        commiter_email: ${{ vars.COMMITER_EMAIL }}
        commiter_name: ${{ vars.COMMITER_NAME }}
      run: python -m unittest discover tests