name: build-image
on:
  push:
    branches:
      - master
jobs:
    build-image:
      runs-on: ubuntu-latest
      steps:
        - name: Git checkout
          uses: actions/checkout@v3       
        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build
          run: |
            VERSION=latest
            echo $VERSION
            echo "Building image"
            docker build -t xmcyber/unique-cidr-manager:$VERSION .
            echo "Pushing to Docker hub"
            docker push xmcyber/unique-cidr-manager:$VERSION